### ISSUE TITLE
window.loadStylesheet is null

### ISSUE THREAD

**Issue by ming-body7** [betsol/ng-ui-router-styles#1]
Hi @slavafomin 
I tried to use the library, it always run the line
log('betsol-load-stylesheet module must be loaded');
      deferred.reject();

seems like window.loadStylesheet is always null.
Any idea on this?

--Ming

**Comment by ming-body7** [comment]
I see. I should load another module(bower install --save betsol-load-stylesheet) first.

**Comment by harm-less** [comment]
But instead of a ```devDependency``` in bower.json, shouldn't this be a regular ```dependency```?
