### ISSUE TITLE
betsol-load-stylesheet module must be loaded

### ISSUE THREAD

**Issue by agrawal-mohit** [betsol/ng-ui-router-styles#6]
How should I be using the following in my project - 

```
var linkElement = window.loadStylesheet('/css/foo.css', function () {
  alert('CSS file loaded!');
});
```

I do not have a single global css file to use, but only for specific states. That is the whole reason i am using this lib. 

Thanks

**Comment by slavafomin** [comment]
Hello! Thank you for your interest in this module!

You should specify path to your CSS files in your states configuration.

Please see the README.
